contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    - https://dl-cdn.alpinelinux.org/alpine/edge/community
    - https://dl-cdn.alpinelinux.org/alpine/edge/testing
  packages:
    - alpine-base
    - build-base
    - bash
    - zsh
    - go
    - git
    - ko
    - docker
    - kind
    - gopls
    - apko

accounts:
  groups:
    - groupname: vscode
      gid: 1000
  users:
    - username: vscode
      uid: 1000
      gid: 1000
  run-as: 1000

entrypoint:
  command: /bin/bash

archs:
  - amd64
  - aarch64
