on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

name: Publish latest images

jobs:
  build:
    name: publish latest
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
    - uses: actions/checkout@v4
    - uses: ko-build/setup-ko@v0.6
    - run: ko publish --base-import-paths ./cmd/...
