on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

name: build-test-publish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-
    - run: go env
    - name: go build
      run: go build -v ./...
    - name: go test
      run: go test -v ./...

  e2e:
    name: e2e tests
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.20.x
    - uses: ko-build/setup-ko@v0.6
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-
    - uses: chainguard-dev/actions/setup-kind@main
      with:
        k8s-version: v1.23.x
    - uses: vdemeester/setup-tektoncd@main
      with:
        pipeline: v0.40.x
        pipeline-feature-flags: '{"enable-api-fields": "alpha"}'
    - name: install manual-approval-gate custom task
      run: |
        kubectl create namespace tekton-remote-resolution
        ko apply --local -f config/
  
  publish:
    name: publish latest
    runs-on: ubuntu-latest
    needs: [ build ]

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.20.x
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: ko-build/setup-ko@v0.6
    - run: |
        ko publish --push=${{ github.event_name != 'pull_request' }} --base-import-paths ./cmd/resolver
